### ISSUE TITLE
[Modal] multi-view support

### ISSUE THREAD

**Issue by ashjtan** [square/maker#185]
### Feature request

There is not a lot of support from the `modalApi` for implementing modals that have multiple different views or screens, i.e. going through a flow. It would be nice to have some sort of built-in functionality for this, e.g. `modalApi.goTo()` or some variation, which can mimic the formatting of `modalApi.open()`, except it just replaces the current component open in the modal with a different component.

It could also provide a nice basis to adding built-in transitions/animations between the views.

### Why?

Right now, in order to implement modals that have multiple views, in practice it ends up something like this:

```
<template>
   <Screen1Component v-if="currentScreen === Screen1" />
   <Screen2Component v-else-if="currentScreen === Screen2" />
</template>

<script>
   const SCREENS = [Screen1, Screen2];

   data() { ... currentScreen: Screen1 )
</script>
```

which can really muddy up the template. The template ends up being a list of all the possible wrapper components that could be showing (i.e. each of the views), rather than a more accurate representation of what is showing on the template at one given time. It is also much more difficult to trace the flow of components in the order in which they would appear, since they're all sitting in the same one wrapper component.

### Alternatives

All in all, this is a general suggestion, and the details of implementation definitely need more deliberation.

**Comment by landondurnan** [comment]
We've tried to manage this in the past in Orbit and it's very challenging. It's one thing if it's a linear flow, but soon after there's conditionals that create branching paths. Or all of a sudden we're doing AB Tests and have to pollute the requirements of navigation and page tracking in a UI component that was never designed for that.

I don't think we should enable functionality like this primarily because there is already better versions of this leveraging routing and regular pages. Recreating a solution like this with modals is ill-advised because of the overwhelming extra work necessary to manage it.

Modals by their definition is meant to open, do something, and close. If we're in a scenario where we're doing anything else, it probably should not be a modal.

**Comment by ashjtan** [comment]
> @landondurnan: Modals by their definition are meant to open, do something, and close. If we're in a scenario where we're doing anything else, it probably should not be a modal.

it's interesting that u mention this, because i figured that this feature has been considered, and that there was a reason it wasn't in the works (reason particularly being: we don't want to encourage multi-view modals). i feel like we have a _lot_ of it (i mean pages and pages worth of content, whole user flows taking place in modals), and if we want to move towards using pages instead, we need to communicate this directly with design.

**Comment by landondurnan** [comment]
@ashjtan You're right, this definitely is something that requires additional alignment with design and an appropriate place for engineering to explain better alternatives. Our current scenarios where we have been overusing modals has had a considerable amount of discussion internally. At minimum this issue helps create a reference to explain why we're not pursuing it due to the complications it creates.
