### ISSUE TITLE
Pin Code Input

### ISSUE THREAD

**Issue by Ryguy11** [square/maker#220]
### Figma link

https://www.figma.com/file/SHY7Z7PbcVssjIJVuJ3IwU/%F0%9F%8D%81-Maker?node-id=10790%3A5819

### Description

The Pin Code Input component will be created to handle the input of different one time passwords or pin code entries. It will be a dynamic length input that is adjustable via prop. The Pin Code will need to auto focus the next input when a number is entered, and emit the code when completed. The Pin Code Input will need an error state and error styling to let the user know if the Pin they entered is invalid.

### API

Props:
- pinLength: number, default 6 - length of inputs to display
- disabled: boolean, default false - should disable code inputs

Event:
- complete: emit the completed PIN code

Slots:
- error: error slot that will display below the pin input

### Theme support

Given that the Pin Inputs will be a collection of Maker inputs, theme'ing should be applied in a similar manner as the inputs.

**Comment by landondurnan** [comment]
Thanks @Ryguy11 

Primarily we should try to determine if we're going to internally use the Input component and then weigh the costs of either doing it or not.

If not, then we may want to mimic the same API noted here, which I think you've done for the most part:
https://github.com/square/maker/tree/master/src/components/Input#props

Probably need an invalid state. Not sure if we want to support different variants. And we don't need prefix / suffix output. 

If we do use the input component internally:
Pros: much of the styling and props are supports and it will inherit any theming controls we add.
Cons: likely need different events and styling for "pin code" that isn't exactly the same as an input with a password.

Gut feel on this is we should simply duplicate what we need rather than use the input internally.

**Comment by landondurnan** [comment]
@Ryguy11 You had mentioned in passing this component exists externally in a couple other components, would you be willing to create a Draft PR pushing that component into Maker? Include any changes you think necessary to match the API suggestions above -- but depending on bandwidth we can determine resourcing to finalize the code around it.

**Comment by pretzelhammer** [comment]
ryguy11 merged his PR into Maker which closes this issue
