### ISSUE TITLE
MButton Flex Layout is Broken In Firefox and Safari

### ISSUE THREAD

**Issue by tatems** [square/maker#236]
### Bug description

When trying to use an `MButton` inside a flex layout, it will behave as if it was much smaller than it actually is, which can cause layout issues (as seen below).

Chrome Example (not broken):
![Screen Shot 2022-03-03 at 10 15 51 AM](https://user-images.githubusercontent.com/3402466/156595991-e01f8352-8ebc-4215-8742-b918c85ab455.png)

Firefox Example (broken):
![Screen Shot 2022-03-03 at 10 12 52 AM](https://user-images.githubusercontent.com/3402466/156596036-082839fe-993a-40c1-a4df-8892f4adf5bc.png)

Safari Example (broken):
![image](https://user-images.githubusercontent.com/3402466/156596763-f410b7a9-51f6-495c-8622-0ad035e0d3f4.png)

### Reproduction

https://codesandbox.io/s/m-button-flex-weirdness-3tyjgd?file=/src/App.vue

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 91.40 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  npmPackages:
    @square/maker: ^6.7.1 => 6.7.1 
    vue: ^2.6.14 => 2.6.14 
    webpack: ^5.1.3 => 5.1.3 
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by pretzelhammer** [comment]
Uhhh, it's probably rendering inconsistently between browsers because you made some weird CSS choices. I don't understand why you're trying to size flex children using `width` and `min-content` here:

```css
.input {
    width: 100%;
}

.button {
    min-width: min-content;
}
```

I changed those classes to use the `flex` property, which is what I think you should be using to size flex children, to this:

```css
.input {
	width: 0;
	flex: 1 0 auto;
}

.button {
	flex: 0 0 auto;
}
```

And it now renders consistently between browsers:

![Pasted_Image_3_16_22__9_41_AM](https://user-images.githubusercontent.com/7769424/158604214-ee6a3a22-599b-49a4-b162-a6e6e13a8b38.png)

In this particular context:
- `flex: 0 0 auto;` means _"Don't grow or shrink this child, let it determine its own size"_.
- `width: 0; flex: 1 0 auto;` means _"Grow this child to accommodate all available remaining space not already taken by other children"_.

Anyway, does this fix your problem? Can you simply adjust the CSS in your application code?
